### ISSUE TITLE
Ticket tracker: margin on the left seems too big

### ISSUE THREAD

**Issue by skyjur** [django/code.djangoproject.com#65] opened 2016-07-25 09:03 UTC
I think the margin on the left is 2 times too big, is it just me? Anyone else seeing this too?

![selection_284](https://cloud.githubusercontent.com/assets/321391/17095949/ecad8f7a-524e-11e6-8b9b-4cf902518391.png)

**Comment by timgraham** [comment] 2016-07-25 09:08
Duplicate of https://github.com/django/djangoproject.com/issues/379. Do you think left aligning the container instead of centering it would be an improvement?

**Comment by skyjur** [comment] 2016-07-25 09:25
Headers have max-width set to 1400px, so I tried that and it seems to nicely aligning everything with the header for me:

```
.full-width [role="main"] {
    max-width: 1400px;
    
}
```

![selection_285](https://cloud.githubusercontent.com/assets/321391/17096571/eacf925e-5251-11e6-849e-18c4ccea11e7.png)

Looks okay when resized as well:
![selection_286](https://cloud.githubusercontent.com/assets/321391/17096584/f6c1ced8-5251-11e6-96ac-176bee295071.png)

**Comment by skyjur** [comment] 2016-07-28 23:17
Made a pull request 
https://github.com/django/code.djangoproject.com/pull/66

**Closed** 2016-08-04 12:30 UTC
