### ISSUE TITLE
New Ticket Login Confusing

### ISSUE THREAD

**Issue by jtpereyda** [django/code.djangoproject.com#64] opened 2016-03-28 18:48 UTC
Django's CONTRIBUTING guide currently points to the New Ticket page: https://code.djangoproject.com/newticket

If you're not logged in, this won't work:
![dango new ticket report](https://cloud.githubusercontent.com/assets/244969/14086388/bff3ab04-f4d9-11e5-9cf8-2065a552c685.PNG)

If you click the "do so" link, you get a login that makes it look like you need to create a new account:
![django new ticket report login](https://cloud.githubusercontent.com/assets/244969/14086429/e5826a54-f4d9-11e5-958b-4ed3e5a06ba3.PNG)

Hmm... Now how do I create an account? If I click cancel, by the way, I go here:
![django new ticket report login cancel](https://cloud.githubusercontent.com/assets/244969/14086450/04a00ae0-f4da-11e5-9dd7-aaf14ce3c25b.PNG)

OK, no good. At this point, I commenced clicking around the site for a while. I finally ended up at [https://code.djangoproject.com/](). While that is a separate subdomain, it looks on the project page like only one of many pages. On this page, there is a link that says "log in with a Github account." Finally, I clicked this link, logged in, and went back to file my bug.

I think my confusion (and perhaps many others') could be mitigated by:
1. Adding a "login with Github link" to the new ticket page, and/or adding a "create a Django Project account" link. According to the DRY principle, this suggests:
2. Adding a unified login page to which both https://code.djangoproject.com/ and the default "not logged in" pages will point to. This login page will have all the options, so that none of them get forgotten or need to be maintained separately.
3. Possibly making a "log in" button more prominent on the Django Project site. This is a bigger design decision though.
4. Give the "Authorization required." page links to login/registration options.

**Comment by timgraham** [comment] 2016-03-28 23:34
Duplicate of https://github.com/django/djangoproject.com/issues/533

**Comment by timgraham** [comment] 2016-03-28 23:36
Actually I'll leave this one open and close the other.

**Comment by felixxm** [comment] 2024-02-28 12:29
Login views looks better now. IMO this is fixed.

**Closed by felixxm** 2024-02-28 12:29 UTC
