### ISSUE TITLE
doc-floating-warning & fragment links

### ISSUE THREAD

**Issue by matsaman** [django/code.djangoproject.com#81] opened 2017-01-26 18:42 UTC
On pages with the #dev-warning, #outdated-warning, .doc-floating-warning, etc. fixed bar at top, some JS is being used to fix positioning after load so fragment links (foo#section) align you properly (so the heading isn't obscured by the fixed bar at top), but... it's not very reliable, and requires JS.

Example pages that should have this yellow or red bar at top:
https://docs.djangoproject.com/en/dev/releases/1.7/#app-registry-consistency
https://docs.djangoproject.com/en/1.7/releases/1.7/#app-registry-consistency

You can compensate for such top bars without JS, with CSS alone kinda like this:
```.section > span[id]:first-child { padding-top: 38px; }```

**Comment by timgraham** [comment] 2017-01-26 18:47
Duplicate of https://github.com/django/djangoproject.com/issues/220.

**Closed by timgraham** 2017-01-26 18:47 UTC
