### ISSUE TITLE
Trac RSS links broken

### ISSUE THREAD

**Issue by medmunds** [django/code.djangoproject.com#204] opened 2024-06-28 20:08 UTC
When you are already logged into Django's Trac, the RSS links go to a login page rather than the RSS feed, and there's no obvious way to actually get the RSS.

To reproduce:

1. Log into [Trac](https://code.djangoproject.com) using a GitHub account. [I haven't tested with a Trac account.]
2. Go to https://code.djangoproject.com/timeline or https://code.djangoproject.com/query (default or with any query options)
3. Scroll to the bottom of the page and click the "RSS Feed" link

Results: you are redirected to the login page (despite already being logged in), with the query "referer" param set to the RSS feed url. But trying to login again there (with GitHub) sends you to the Trac homepage rather than the RSS feed (likely because of #195).

Expected: you should end up on the appropriate RSS feed

Note: these RSS feeds don't actually require login. Also, the "Comma-delimited Text" and "Tab-delimited Text" links at the bottom of the query page don't have this problem.

Workaround: either logout first (the links aren't broken when you're logged out), or ignore the RSS links and instead just append a `format=rss` query param to the query/timeline URL.

**Comment by bmispelon** [comment] 2024-06-29 09:23
Hi and thanks for the report, it's much appreciated.

I can indeed reproduce the behavior you're describing, and I agree that it doesn't work as it should.

These links are generated automatically by Trac, so I've had a dive in the source code 🤿 . It seems that Trac uses a special [`auth_link`](https://github.com/edgewall/trac/blob/e011e2d023001fe6e17ca7bd83d30a96e6046cfa/trac/web/chrome.py#L314-L323) for some of the links, including the RSS ones. As you've correctly identified, this breaks because of #195 .

Unfortunately I don't see a way to work around Trac's behavior here (not without reimplementing a bunch of templates which is not maintainable), so the solution that remains is to fix #195 .

So I'm going to close this issue as a duplicate, but please reopen (or comment) if you have an idea for how to solve this specific issue independently of #195.

Have a nice day! ✨

**Comment by bmispelon** [comment] 2024-06-29 11:09
Of course after writing this comment I realized there was an easy workaround after all: #206

**Closed** 2024-07-01 11:37 UTC
